backend:
  name: github
  repo: harshakamaduranga/Love-Of-Dish
  branch: main
  base_url: https://loveofdish.vercel.app
  auth_endpoint: /auth

media_folder: "images"
public_folder: "/images"

collections:
  - name: "dishes"
    label: "Dishes"
    folder: "content/dishes"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Dish Name", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Dish Image (Thumbnail)", name: "image", widget: "image"}
      - {label: "Video Link (YouTube)", name: "video", widget: "string", required: false, hint: "Paste YouTube link here"}
      - {label: "Description", name: "body", widget: "markdown"}
